language: go
go:
  - 1.9.x
  - "1.10"
  - "1.10.1"
  - "1.10.2"
  - "1.10.3"
script: make test
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database faqaas_test;' -U postgres
  - psql -U postgres -d faqaas_test -f schema.sql
