#!/bin/bash
set -euxo pipefail

export DATABASE_URL=postgres://mat:@localhost/faqaas?sslmode=disable
export PORT=8080
export SUPPORTED_LOCALES=en,de,fr,es,it,nl,pt,pt-BR,da,sv,no,ru,ar,zh
export JWT_KEY=secret

go run main.go
